name: Stable Build

on:
  push:
    branches:
      - main
    paths:
      - stable
      - .github/workflows/docker-build-stable.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup dynamic build ARGs
        id: getargs
        run: echo "::set-output name=version::$(cat ./stable/VERSION)"
      -
        name: Setup Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,latest
          labels: |
            org.opencontainers.image.vendor=The Goofball - goofball222@gmail.com
            org.opencontainers.image.description=Pritunl Server
            org.opencontainers.image.version=${{ steps.getargs.outputs.version }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./stable
          file: ./stable/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ steps.getargs.outputs.version }}
